export const GEMINI_LIVE_LANGUAGE_OPTIONS = [
  { value: 'ar-EG', label: 'Arabic (Egypt)' },
  { value: 'de-DE', label: 'German (Germany)' },
  { value: 'en-US', label: 'English (US)' },
  { value: 'es-US', label: 'Spanish (US)' },
  { value: 'fr-FR', label: 'French (France)' },
  { value: 'hi-IN', label: 'Hindi (India)' },
  { value: 'id-ID', label: 'Indonesian (Indonesia)' },
  { value: 'it-IT', label: 'Italian (Italy)' },
  { value: 'ja-JP', label: 'Japanese (Japan)' },
  { value: 'ko-KR', label: 'Korean (Korea)' },
  { value: 'pt-BR', label: 'Portuguese (Brazil)' },
  { value: 'ru-RU', label: 'Russian (Russia)' },
  { value: 'nl-NL', label: 'Dutch (Netherlands)' },
  { value: 'pl-PL', label: 'Polish (Poland)' },
  { value: 'th-TH', label: 'Thai (Thailand)' },
  { value: 'tr-TR', label: 'Turkish (Turkey)' },
  { value: 'vi-VN', label: 'Vietnamese (Vietnam)' },
  { value: 'ro-RO', label: 'Romanian (Romania)' },
  { value: 'uk-UA', label: 'Ukrainian (Ukraine)' },
  { value: 'bn-BD', label: 'Bengali (Bangladesh)' },
  { value: 'en-IN', label: 'English (India)' },
  { value: 'mr-IN', label: 'Marathi (India)' },
  { value: 'ta-IN', label: 'Tamil (India)' },
  { value: 'te-IN', label: 'Telugu (India)' }
] as const

export const GEMINI_LIVE_VOICE_OPTIONS = [
  { value: 'Zephyr', label: 'Zephyr', gender: 'neutral' },
  { value: 'Puck', label: 'Puck', gender: 'male' },
  { value: 'Charon', label: 'Charon', gender: 'male' },
  { value: 'Kore', label: 'Kore', gender: 'female' },
  { value: 'Fenrir', label: 'Fenrir', gender: 'male' },
  { value: 'Leda', label: 'Leda', gender: 'female' },
  { value: 'Orus', label: 'Orus', gender: 'male' },
  { value: 'Aoede', label: 'Aoede', gender: 'female' },
  { value: 'Callirrhoe', label: 'Callirrhoe', gender: 'female' },
  { value: 'Autonoe', label: 'Autonoe', gender: 'female' },
  { value: 'Enceladus', label: 'Enceladus', gender: 'male' },
  { value: 'Iapetus', label: 'Iapetus', gender: 'male' },
  { value: 'Umbriel', label: 'Umbriel', gender: 'neutral' },
  { value: 'Algieba', label: 'Algieba', gender: 'male' },
  { value: 'Despina', label: 'Despina', gender: 'female' },
  { value: 'Erinome', label: 'Erinome', gender: 'female' },
  { value: 'Algenib', label: 'Algenib', gender: 'male' },
  { value: 'Rasalgethi', label: 'Rasalgethi', gender: 'male' },
  { value: 'Laomedeia', label: 'Laomedeia', gender: 'female' },
  { value: 'Achernar', label: 'Achernar', gender: 'male' },
  { value: 'Alnilam', label: 'Alnilam', gender: 'male' },
  { value: 'Schedar', label: 'Schedar', gender: 'male' },
  { value: 'Gacrux', label: 'Gacrux', gender: 'male' },
  { value: 'Pulcherrima', label: 'Pulcherrima', gender: 'female' },
  { value: 'Achird', label: 'Achird', gender: 'male' },
  { value: 'Zubenelgenubi', label: 'Zubenelgenubi', gender: 'male' },
  { value: 'Vindemiatrix', label: 'Vindemiatrix', gender: 'female' },
  { value: 'Sadachbia', label: 'Sadachbia', gender: 'male' },
  { value: 'Sadaltager', label: 'Sadaltager', gender: 'male' },
  { value: 'Sulafat', label: 'Sulafat', gender: 'female' }
] as const

export type GeminiLiveLanguageCode = (typeof GEMINI_LIVE_LANGUAGE_OPTIONS)[number]['value']
export type GeminiLiveVoiceName = (typeof GEMINI_LIVE_VOICE_OPTIONS)[number]['value']
